# Generated by Django 4.0.5 on 2022-08-31 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_comment_body_alter_comment_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата публикации'),
        ),
    ]
